// Role and permission definitions for the apartment management system

export const PERMISSIONS = {
  // Apartment permissions
  VIEW_APARTMENTS: 'view_apartments',
  MANAGE_APARTMENTS: 'manage_apartments',

  // Tenant permissions
  VIEW_TENANTS: 'view_tenants',
  MANAGE_TENANTS: 'manage_tenants',

  // Maintenance permissions
  VIEW_MAINTENANCE: 'view_maintenance',
  MANAGE_MAINTENANCE: 'manage_maintenance',

  // Billing permissions
  VIEW_BILLING: 'view_billing',
  MANAGE_BILLING: 'manage_billing',

  // User management permissions
  VIEW_USERS: 'view_users',
  MANAGE_USERS: 'manage_users',

  // Dashboard permissions
  VIEW_DASHBOARD: 'view_dashboard',

  // Settings permissions
  MANAGE_SETTINGS: 'manage_settings',
};

export const ROLE_PERMISSIONS = {
  superadmin: [
    PERMISSIONS.VIEW_APARTMENTS,
    PERMISSIONS.MANAGE_APARTMENTS,
    PERMISSIONS.VIEW_TENANTS,
    PERMISSIONS.MANAGE_TENANTS,
    PERMISSIONS.VIEW_MAINTENANCE,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_SETTINGS,
  ],
  admin: [
    PERMISSIONS.VIEW_APARTMENTS,
    PERMISSIONS.MANAGE_APARTMENTS,
    PERMISSIONS.VIEW_TENANTS,
    PERMISSIONS.MANAGE_TENANTS,
    PERMISSIONS.VIEW_MAINTENANCE,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  manager: [
    PERMISSIONS.VIEW_APARTMENTS,
    PERMISSIONS.MANAGE_APARTMENTS,
    PERMISSIONS.VIEW_TENANTS,
    PERMISSIONS.MANAGE_TENANTS,
    PERMISSIONS.VIEW_MAINTENANCE,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  tenant: [
    PERMISSIONS.VIEW_MAINTENANCE,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
};
